### PR TITLE
Add a simple pyam tutorial

### PR DESCRIPTION
**Pull request by danielhuppmann**
Thanks @olejandro for making available the scenario data in this way! I wanted to work more with the frictionless datapackage format anyway, so this is a nice opportunity for me to explore this - see a simple notebook attached, which could serve as a starting point for a tutorial on how to analyze the scenario results with the [pyam package](https://github.com/iamconsortium/pyam).

[Note: pyam already has a native [read_datapackage()](https://pyam-iamc.readthedocs.io/en/stable/api/io.html#pyam.read_datapackage) function, but this only works if the resource-names and table formats are directly compatible with pyam - hence the need to do a bit more elaborate work in this notebook.]

A rendered version of this notebook can be found [here](https://github.com/danielhuppmann/ireland-carbon-budget-scenarios-2021/blob/pyam-tutorial/TIMES-pyam-tutorial.ipynb)

A few issues that I noted:
 - not sure if the way that the unit is stored is standard, or if a better approach in line with the SENTINEL or OEP projects?
 - as already pointed out by @ludee on [Twitter](https://twitter.com/LudwigHuelk/status/1436820581807239173), adding metadata (license, authors, information on the model version, documentation, scenario protocols, source data, scientific manuscript, etc.) would be very helpful
 - having some definitions on the nomenclature (e.g., what does "PWR-MSW" mean) included in this repo or as metadata would be helpful (see related work at https://github.com/iamconsortium/nomenclature)

### CODE REVIEW

**Comment by danielhuppmann** [comment]
FYI @suvayu @jh-RLI @christian-rli @henhuy - any comments would be appreciated!

**Comment by olejandro** [comment]
Thanx, @danielhuppmann for all the feedback and even creating a tutorial for how to use pyam with this dataset!
It is our first datapackage using frictionless, so there are definitely quite some things to figure out. :-)

**Comment by suvayu** [comment]
Hi @danielhuppmann, thanks for bringing this to my attention.  I tried reading it into `pandas` and `xarray` using [`friendly_data`](https://github.com/sentinel-energy/friendly_data), and it worked smoothly.  Great testament to the utility of publishing data in open formats (thanks @olejandro) and working on tools like `pyam` and `friendly_data`!
```
In [5]: from friendly_data.dpkg import read_pkg

In [6]: from friendly_data.converters import to_df, to_mfdst

In [7]: pkg = read_pkg("datapacakge.json")

In [8]: dst = to_mfdst(pkg.resources)  # whole data package as a single xarray.Dataset

In [9]: dst
Out[9]: 
<xarray.Dataset>
Dimensions:                      (dim_0: 27407, dim_1: 4)
Coordinates:
  * dim_0                        (dim_0) int64 0 1 2 3 ... 27404 27405 27406
  * dim_1                        (dim_1) object 'scenarioName' ... 'value'
Data variables: (12/101)
    agr_fec                      (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ind-caf_fec                  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ind-con_fec                  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ind-eoe_fec                  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ind-fab_fec                  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ind-mae_fec                  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    ...                           ...
    tra_passenger_land_fuelcons  (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    tra_passenger_land_mode-l    (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    tra_passenger_land_mode-m    (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    tra_passenger_land_mode-s    (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    tra_passenger_land_mode      (dim_0, dim_1) object 'Mitigation_CAP21_A25E...
    tra_turs_fuelcons            (dim_0, dim_1) object 'Mitigation_CAP21_A25E...

In [10]: dfs = [to_df(r) for r in pkg.resources]   # data package as a list of pandas.DataFrame

In [11]: dfs[0]
Out[11]: 
                 scenarioName seriesName  period     value
0     Mitigation_CAP21_A25E65     AGRBDL    2027  2.575706
1     Mitigation_CAP21_A25E65     AGRBDL    2028  2.781921
2     Mitigation_CAP21_A25E65     AGRBDL    2029  2.990765
3     Mitigation_CAP21_A25E65     AGRBDL    2030  3.205089
4     Mitigation_CAP21_A25E65     AGRBDL    2031  3.426936
...                       ...        ...     ...       ...
5354            No_Mitigation     AGRLPG    2046  0.880985
5355            No_Mitigation     AGRLPG    2047  0.901638
5356            No_Mitigation     AGRLPG    2048  0.922216
5357            No_Mitigation     AGRLPG    2049  0.942730
5358            No_Mitigation     AGRLPG    2050  0.963188

[5359 rows x 4 columns]
```

---
I have one comment though, if the resource entries had the `primaryKey` set, the above dataframe could also set the columns listed there as a hierarchical index.

So something like this:
```
{
  ...
  "primaryKey": ["scenarioName", "seriesName", "period"]
}
```

Would be read as:
```
In [11]: dfs[0].set_index(["scenarioName", "seriesName", "period"])
Out[11]: 
                                              value
scenarioName            seriesName period          
Mitigation_CAP21_A25E65 AGRBDL     2027    2.575706
                                   2028    2.781921
                                   2029    2.990765
                                   2030    3.205089
                                   2031    3.426936
...                                             ...
No_Mitigation           AGRLPG     2046    0.880985
                                   2047    0.901638
                                   2048    0.922216
                                   2049    0.942730
                                   2050    0.963188

[5359 rows x 1 columns]
```
Much easier to query dataframes with a meaningful index :)

---
The CLI also works rather well (although I think it needs a lot of polishing).
```
$ friendly_data describe datapackage.json 
name: ireland-carbon-budget-scenarios-2021
title: Carbon Budget Scenarios for Ireland's Energy System, 2021-50
licenses: CC-BY-4.0

resources:
---
path: data/agr_fec.csv
fields: scenarioName, seriesName, period, value
---
path: data/ind-caf_fec.csv
fields: scenarioName, seriesName, period, value
---
path: data/ind-con_fec.csv
fields: scenarioName, seriesName, period, value
---
...
```

**Comment by olejandro** [comment]
Thanx, @suvayu! I can definitely set `primaryKey`.

**Comment by olejandro** [comment]
@danielhuppmann and @suvayu, I've added scenarios and series resources as data to the datapackage.json. Is it a good way? I can see that frictionless fails to validate it, because it cannot find the files (only when the validation is run locally, not on github), although it should not even look for them (based on documentation). Would it be useful to add foreign keys pointing to scenarios and series to the relevant resources?

**Pull request merged**
